---
- hosts: all
  roles:
    - { role: 'criar-usuario', tags: 'usuario' }

- hosts: rkeservers
  roles:
    - { role: 'preparar-nodes', tags: 'nodes'}
    - { role: 'instalar-docker', tags: 'docker'}
  become: yes

- hosts: workstation
  roles:
    - { role: 'preparar-workstation', tags: 'workstation' }
  become: yes

- hosts: workstation
  roles:
    - { role: 'criar-cluster', tags: 'cluster'}