- name: Instalando pacotes necessários
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - wget
    - curl
    - nfs-utils
    - vim

- name: Instalando o kubectl
  shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  args:
    chdir: /usr/local/bin
    creates: kubectl
    warn: false

- name: Concedendo permissão de execução ao Kubectl
  ansible.builtin.file:
    path: /usr/local/bin/kubectl
    mode: '755'

- name: Instalando o Rke
  shell: curl -s https://api.github.com/repos/rancher/rke/releases/latest | grep browser_download_url | grep amd64 | grep linux | cut -d '"' -f 4 | wget -qi -
  args:
    chdir: /usr/local/bin/
    creates: rke_linux-amd64
    warn: false

- name: Concedendo permissão de execução ao RKE
  ansible.builtin.file:
    path: /usr/local/bin/rke_linux-amd64
    mode: '755'

- name: Movendo binario do Rke para o path local
  command: mv /usr/local/bin/rke_linux-amd64 /usr/local/bin/rke

- name: Instalando o Helm
  shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  args:
    chdir: /usr/local/bin
    creates: helm
    warn: false

- name: Criando arquivo de configuração do cluster RKE
  template:
    src: 'templates/rke-cluster.j2'
    dest: '~{{ user }}/cluster.yaml'
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"