- name: Adicionando Repositorio Docker
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/centos_o.repo 

- name: Instalando somente o containerd
  yum:
    name: containerd
    state: present

- name: Criando o diretorio de configuração do containerd
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Criando arquivo de configuração do containerd
  shell: containerd config default | tee /etc/containerd/config.toml
  args:
    warn: false
  become: yes

- name: Reiniciando o containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
  become: yes