  - name: Atualizando pacotes do sistema
    yum:
      name: '*'
      state: latest

  - name: Carregando modulos do kernel para o Rke
    modprobe:
      name: "{{ item }}"
      state: present
    with_items: "{{ kernel_modules }}"

  - name: Desativando a memoria swap (1/2)
    shell: swapoff -a
   
  - name: Desativando a memoria swap (2/2)
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+.*)$'
      replace: '# \1'
  
  - name: Alterando a entrada sysctl
    sysctl:
      name: '{{ item.key }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
    with_items:
      - {key: net.bridge.bridge-nf-call-ip6tables, value: 1}
      - {key: net.bridge.bridge-nf-call-iptables,  value: 1}
      - {key: net.ipv4.ip_forward,  value: 1}

  - name: Liberando as portas TCP necessárias no firewall
    firewalld:
      port: "{{ item }}/tcp"
      permanent: yes
      state: enabled
    with_items: "{{ portas_tcp }}"

  - name: Liberando as portas UDP necessárias no firewall
    firewalld:
      port: "{{ item }}/udp"
      permanent: yes
      state: enabled
    with_items: "{{ portas_udp }}"
    notify:
      - Restart Firewalld

  - name: Permitir encaminhamento de TCP SSH
    replace:
      path: /etc/ssh/sshd_config
      regexp: '#AllowTcpForwarding'
      replace: 'AllowTcpForwarding'
    notify:
      - Restart SSHD