  - name: Atualizando pacotes do sistema
    yum:
      name: '*'
      state: latest

  - name: Adicionando usuario Rke admin
    user:
      name: rke
      shell: /bin/bash
   
  - name: Creando arquivo sudo
    file:
      path: /etc/sudoers.d/rke
      state: touch
  
  - name: Conceder permissão sudo ao usuario Rke
    lineinfile:
      path: /etc/sudoers.d/rke
      state: present
      line: 'rke ALL=(ALL:ALL) NOPASSWD: ALL'
   
  - name: Definindo chave de autorização ssh
    authorized_key:
      user: rke
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: Carregando modulos do kernel para o Rke
    modprobe:
      name: "{{ item }}"
      state: present
    with_items: "{{ kernel_modules }}"

  - name: Desativando a memoria swap (1/2)
    shell: swapoff -a
   
  - name: Desativando a memoria swap (2/2)
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+.*)$'
      replace: '# \1'
  
  - name: Alterando a entrada sysctl
    sysctl:
      name: '{{ item.key }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
    with_items:
      - {key: net.bridge.bridge-nf-call-ip6tables, value: 1}
      - {key: net.bridge.bridge-nf-call-iptables,  value: 1}
      - {key: net.ipv4.ip_forward,  value: 1}

  - name: Liberando as portas necessárias no firewall
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    with_items: "{{ portas }}"